server:
  port: 6677
spring:
  application:
    name: consumer

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group-A
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
