server:
  port: 6666
spring:
  application:
    name: producer

  kafka:
    bootstrap-servers: localhost:9092
    # producer:
    #   key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #   value-serializer: org.apache.kafka.common.serialization.StringSerializer
    #   acks: all
    #   retries: 3
    #   batch-size: 16384
    #   linger-ms: 1
    #   buffer-memory: 33554432
